### ISSUE TITLE
lua error from spawning a wall

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#34]
[f=0000176] Error: LuaRules::RunCallIn: error = 2, UnitCloaked, [Internal Lua error: Call failure] [string "lups/lups.lua"]:190: attempt to call field 'ActivateMaterial' (a nil value)
stack traceback:
    [string "lups/lups.lua"]:190: in function 'SetUnitLuaDraw'
    [string "lups/ParticleClasses/unitcloaker.lua"]:281: in function 'Create'
    [string "lups/lups.lua"]:329: in function 'AddParticles'
    [string "LuaRules/Gadgets/lups_cloak_fx.lua"]:156: in function 'UnitCloaked'
    [string "luagadgets/gadgets.lua"]:1429: in function <[string "luagadgets/gadgets.lua"]:1427>
    (tail call): ?

**Comment by gajop** [comment]
This happened when I was trying to hide fires (by cloaking). I'm no longer cloaking fires so it's no longer an issue.
