### ISSUE TITLE
Pushing crates into units should do moderate damage

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#37]

**Comment by silentwings** [comment]
units means what here? evil robots?

**Comment by gajop** [comment]
Yes, but im no longer sure i want this. Using crates as cover seems more
fun, so crates should be indestructable and do no dmg

**Comment by gajop** [comment]
imo disable all damage from collisions or falling
stuff is getting damaged nearly randomly and serves no gameplay service
