### ISSUE TITLE
make smoke image

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#39]
to replace https://github.com/SpringCabal/Gravitas/blob/c3f1e385e4590558b9138aeeba663b75a81c53d0/Bitmaps/smoke.png

**Comment by silentwings** [comment]
also, https://github.com/SpringCabal/Gravitas/blob/master/Bitmaps/GPL/smoke_orange.png

**Comment by ashdnazg** [comment]
smoke_orange is mine
