### ISSUE TITLE
Skybox: space skybox

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#44]
We're in space (spaceship), so a space background would be neat!

**Comment by silentwings** [comment]
I know how to do this with a "normal" map, but Gravity seems not to have a mapinfo etc etc.

**Comment by gajop** [comment]
I'll compile the map tomorrow. It's currently using Brownwood's map. 
Still, feel free to make skybox/mapinfo at any time and it can be added to Brownwood locally while developing.

**Comment by silentwings** [comment]
Hmm, no idea how to actually make a skybox - there is a compilation step iirc and I don't think anyone made new ones for years. There are plenty of really nice ones on https://springrts.com/phpbb/viewtopic.php?f=56&t=11009&hilit=skyboxes.

**Comment by PicassoCT** [comment]
Wrong.. jw uses a standard new one.. its just rotating..
