### ISSUE TITLE
Barrel/canister explosions should reflect their range

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#45]
Explosion should reflect range (either entire range, larger or smaller):
https://github.com/SpringCabal/Gravitas/blob/master/LuaRules/Gadgets/unit_expl_barrels.lua#L26
Also should be near instant expansion with up to a second or so fade out

**Comment by silentwings** [comment]
Where is their range defined?

**Comment by gajop** [comment]
Here: https://github.com/SpringCabal/Gravitas/blob/master/LuaRules/Gadgets/unit_expl_barrels.lua#L26
It used to be defined here: https://github.com/SpringCabal/Gravitas/commit/c3f1e385e4590558b9138aeeba663b75a81c53d0#diff-13ae7d56a67d01842787e0ea2b7b32acL16 but you changed that code

**Comment by silentwings** [comment]
I know that - I mean, where is it actually defined? Normally it would be in the unitdef, I just left a palceholder.

Or are you saying that you want explosions of range 200 rather than 150?

**Comment by gajop** [comment]
Ahhh I think we have a misunderstanding, I guess I wasn't clear enough.
The explosion EFFECT should reflect the range (that is I want an explosion
to visibly show that it's affecting units in a 150 or 200 range radius).
Now it's like a small flame that's just around the container, but from that
it's not clear how large the radius is.

2015-04-19 15:59 GMT+09:00 silentwings notifications@github.com:

**Comment by silentwings** [comment]
There should be smoke and a groundflash that reaches out to slightly past 150 - do you see those?

Changing to 200 is no problem.

**Comment by gajop** [comment]
No,
 [f=0000836] Warning: [CCEG::Load] table for CEG "flashnuke" invalid (parse
errors?)

2015-04-19 16:03 GMT+09:00 silentwings notifications@github.com:

**Comment by silentwings** [comment]
I don't have that error. Which Spring version are you using?

**Comment by gajop** [comment]
I use 98.0, but I also tried with the dev version and the results are the
same.
Also it's probably not a case issue (sometimes happens on Linux), as
flashNuke didn't work either.

2015-04-19 16:15 GMT+09:00 silentwings notifications@github.com:

**Comment by silentwings** [comment]
Ok, I also use 98.0. But without having the error I can't debug it, I'm afraid you'll have to look at it. Once it's fixed I'll change the radius.

**Comment by silentwings** [comment]
https://github.com/SpringCabal/Gravitas/commit/b5f1482cae1f58cfeb12a0b0d69df24d22bc4d04 (forgot to commit the flashnuke)

**Comment by gajop** [comment]
works now
