### ISSUE TITLE
Void map

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#50]
If https://github.com/SpringCabal/Gravitas/issues/44 is done, add void parts of the map that player has to jump over. This is going to be done for the final map only probably, either as void water or void ground.

**Comment by silentwings** [comment]
Seems to exist now, I saw through holes in the map

**Comment by gajop** [comment]
Yep, exists, although not perfect (but definitely can be closed).

2015-04-21 16:57 GMT+09:00 silentwings notifications@github.com:
