### ISSUE TITLE
Robot paralyzed (electric field) animation/effect

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#55]

**Comment by silentwings** [comment]
How do things that are paralysed and stuck in an electric field get out again?

**Comment by gajop** [comment]
They usually don't, but they could be pushed out again. The player
character doesn't get stuck as he's not a robot, but instead gets
damaged/killed (currently killed, but maybe just medium damage instead).
Other objects don't get stuck, but those are immobile anyway

2015-04-19 17:55 GMT+09:00 silentwings notifications@github.com:

**Comment by silentwings** [comment]
Won't that result in paralysed robots piling up?

**Comment by gajop** [comment]
Yeah, the goal is to put them all in the static field, but they still
collide with each other so there are no visible artefacts.

2015-04-19 18:27 GMT+09:00 silentwings notifications@github.com:
