### ISSUE TITLE
Make better looking UI

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#58]
Better looking UI: two parts to the left and right of the health bar, which are used to display whether it's the pull or push state.
Example of one part:
https://www.dropbox.com/s/6u39nrzmzha94n5/UI_example.png?dl=0

It should glow in a particular color (different for push and pull) and be really obvious what's the current state.
It's just an indicator (it's not a button).
The user should be informed in another way to use the Q to switch states, maybe a button for switching states (similar to current one, but doesn't need to have an action or show the current state, just switch with a hotkey)

**Comment by silentwings** [comment]
Why two parts? Afaics there is only one piece of information to show.

**Comment by gajop** [comment]
Yeah, but it would look cooler and be symmetric!
Additionally it sorta hints immediately that there's pull and push and it might leave room if we want to allow both things to show.

**Comment by silentwings** [comment]
It's just an indicator (it's not a button). > I think it wold be better as a button, I keep wanting to click it.

**Comment by silentwings** [comment]
https://github.com/SpringCabal/Gravitas/commit/7d9273a5f88fd91c7023c84dd473fe9014ca6c24

Might be even better to have (a single button) for which RMB selects push and PMB selects push. Easy to make this change from current code.
