### ISSUE TITLE
Have robots avoid traps

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#59]
It would be great if we could somehow make robots avoid traps.
Maybe if we made those things collidable.. or blocking=true?
It really needs to be a fake blocking, units should still get stuck in traps (so they would die in fire with the animation or get paralyzed)

**Comment by silentwings** [comment]
What currently controls the robot movement?

**Comment by gajop** [comment]
Null AI and some fight/patrol orders issued.
The point is, for non-hold pos units (and many are such), we want them to
be smart enough to avoid fires automatically while chasing the player.

2015-04-19 19:20 GMT+09:00 silentwings notifications@github.com:

**Comment by silentwings** [comment]
"some fight/patrol orders issued" - from where? I can't see any gadget issuing orders. If orders are issued from multiple places I think this would risk being buggy.

**Comment by gajop** [comment]
anyway the point of this was that units enter traps, even if no move order was given and they just maneuvered into them; 
maybe it could be solved via heatmapping or gadgets that would cause units to get move orders outside of fire when near it

**Comment by silentwings** [comment]
Having played a bit, I think their behaviour is great as it is.

**Comment by gajop** [comment]
Hmm, I'm going to reopen this...
The issue is units will walk into traps and stay their obliviously.
We should look for a way that so that they would consider it an obstacle instead.

(To be clear, it was good enough for the submission, but imo should be changed for the final version, maybe unit AI or heat mapping).
