### ISSUE TITLE
healthbars draw at the wrong height

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#69]
because GetUnitViewPosition returns the wrong positions, which is probably caused by the model height/radius/midpoint/something not being set right

**Comment by silentwings** [comment]
Also, the healthbars shader does not play nicely with LUPS - I bet the healthbars shader is bugged.

**Comment by silentwings** [comment]
I think we should just remove them, at least for now. 

The shader draws arbitrary grey rectangles when inside fires/electrafi (+ might be a pain to fix Floris' shader), and our model radii mean the bars draw at the wrong height anyway.

**Comment by gajop** [comment]
I find them essential for damaging canisters/boss though. I'd rather fix this really

**Comment by silentwings** [comment]
Discovered that also the text on the bars is drawn in slightly the wrong place...

**Comment by silentwings** [comment]
> I find them essential for damaging canisters/boss though. I'd rather fix this really
