### ISSUE TITLE
gravit should stay still while firing

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#71]
or at least, would be good if it doesn't try to chase the things that it moves away

will hopefully mean that stuff is moved in more consistent directions (& maybe also, should drop the attack command of something that is pushed far out of range)

**Comment by silentwings** [comment]
He actually moves his arm while firing, if the target is close - that should definately be stopped.

**Comment by Anarchid** [comment]
Nope, that didn't do that actually.

**Comment by silentwings** [comment]
I saw it happen!

**Comment by silentwings** [comment]
unnecessary after https://github.com/SpringCabal/Gravitas/commit/0e2a8edd730edf377c4e16859c4dcd77e88aee94

**Comment by silentwings** [comment]
unnecessary after https://github.com/SpringCabal/Gravitas/commit/0e2a8edd730edf377c4e16859c4dcd77e88aee94
