### ISSUE TITLE
jump jets lua error

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#79]
[f=0022428] Error: LuaRules::RunCallIn: error = 2, CommandFallback, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_jumpjets.lua"]:493: attempt to index field 'Delay' (a nil value)

Not sure of precise cause, I just jumped a few times in a row with gravit.

**Comment by gajop** [comment]
:S probably api_delay needs to be added (scenario editor already has it so
i didn't get this error)
working on jumpjets now anyway

2015-04-21 1:52 GMT+09:00 silentwings notifications@github.com:
