### ISSUE TITLE
add to rapid?

### ISSUE THREAD

**Issue by abma** [SpringCabal/Gravitas#85]
shall i add it to rapid?

or ...aww.... because of submodules it won't work?!

**Comment by silentwings** [comment]
For now, no.

**Comment by silentwings** [comment]
Ops, didn't mean to close

**Comment by gajop** [comment]
It's not ready for release yet (regardless of the submodule issue).

**Comment by abma** [comment]
for adding the submodule path needs to be fixed:

Cloning into 'libs/chiliui'...
Permission denied (publickey).
fatal: Could not read from remote repository.

https://github.com/SpringCabal/Gravitas/blob/master/.gitmodules

**Comment by gajop** [comment]
Ah, sorry. Should be fine [now:](https://github.com/SpringCabal/Gravitas/commit/fff45b91ff5148a7f680c48e16dc23528741ab23):
`Submodule 'libs/chiliui' (https://github.com/gajop/chiliui.git) registered for path 'libs/chiliui'`
