### ISSUE TITLE
should package as sdz

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/Gravitas#92]
This will fix the wait on first run. With sdd Spring has to hash each file in each sdd individually, with sdz it does not.

**Comment by gajop** [comment]
or we could just distribute the cached version?
PS: we have multiple archives, and all are .sdds

**Comment by silentwings** [comment]
I don't think we can distribute a cached version since iirc the ArchiveCache uses hardcoded full paths.

**Comment by gajop** [comment]
I've also uploaded the changed versions. Please test them (especially the Windows version).
