### ISSUE TITLE
Tooltip improvements

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Gravitas#94]
Tooltips can be made better:
- **Right click**: Move and use the gravity gun (instead of left click, this is confusing as people will try to just press the left click)
- **S**: Stop moving and shooting
- **Q**: Toggle gravity gun
- **W**: Jump

The hotkeys should be bolded or emphasized with colors as above

**Comment by silentwings** [comment]
> Right click: Move and use the gravity gun 

This isn't true - it only works when hovering over a crate/robot/etc.

**Comment by gajop** [comment]
That's the only time it has an effect.
A should be removed because it requires two actions, is technically a
duplicate and has issues like the ability to do area-attack which would
target walls.

2015-04-25 0:23 GMT+09:00 silentwings notifications@github.com:
